// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBwBjEQKhBxKerOx9kW92OwIOeMzG3Cc',
    appId: '1:892793771113:web:945280ef480608e1233ef8',
    messagingSenderId: '892793771113',
    projectId: 'social-media-chatgpt-159e3',
    authDomain: 'social-media-chatgpt-159e3.firebaseapp.com',
    storageBucket: 'social-media-chatgpt-159e3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5IK1DWe_0UW3vumDxVThpEMBUYKvJVL4',
    appId: '1:892793771113:android:3e385d9d20e1d09c233ef8',
    messagingSenderId: '892793771113',
    projectId: 'social-media-chatgpt-159e3',
    storageBucket: 'social-media-chatgpt-159e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMWhr2QqdfeW_wYmx18pcdVAiyfJxJGyc',
    appId: '1:892793771113:ios:5f522d71284f2516233ef8',
    messagingSenderId: '892793771113',
    projectId: 'social-media-chatgpt-159e3',
    storageBucket: 'social-media-chatgpt-159e3.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaChatgpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMWhr2QqdfeW_wYmx18pcdVAiyfJxJGyc',
    appId: '1:892793771113:ios:5f522d71284f2516233ef8',
    messagingSenderId: '892793771113',
    projectId: 'social-media-chatgpt-159e3',
    storageBucket: 'social-media-chatgpt-159e3.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaChatgpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjBwBjEQKhBxKerOx9kW92OwIOeMzG3Cc',
    appId: '1:892793771113:web:610d9065cb40796e233ef8',
    messagingSenderId: '892793771113',
    projectId: 'social-media-chatgpt-159e3',
    authDomain: 'social-media-chatgpt-159e3.firebaseapp.com',
    storageBucket: 'social-media-chatgpt-159e3.firebasestorage.app',
  );

}